f2fs/rapid_gc: Update remaining f2fs_msg macros
Subsequent to a0d6863 ("f2fs: introduce f2fs_<level> macros to wrap f2fs_printk()")

This silences the following compiler errors:

../fs/f2fs/gc.c:35:4: error: implicit declaration of function 'f2fs_msg' [-Werror,-Wimplicit-function-declaration]
                        f2fs_msg(sbi->sb, KERN_INFO, "Catching wakelock for GC");
                        ^
../fs/f2fs/gc.c:40:4: error: implicit declaration of function 'f2fs_msg' [-Werror,-Wimplicit-function-declaration]
                        f2fs_msg(sbi->sb, KERN_INFO, "Unlocking wakelock for GC");
                        ^
../fs/f2fs/gc.c:145:4: error: implicit declaration of function 'f2fs_msg' [-Werror,-Wimplicit-function-declaration]
                        f2fs_msg(sbi->sb, KERN_INFO,
                        ^
../fs/f2fs/gc.c:246:4: error: implicit declaration of function 'f2fs_msg' [-Werror,-Wimplicit-function-declaration]
                        f2fs_msg(sbi->sb, KERN_INFO,
                        ^

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>