ext4: Remove unused 'retval'
Subsequent to 3a3ac01 ("fscrypt: fix race where ->lookup() marks plaintext dentry as ciphertext")

This silences the following compiler warning:

../fs/ext4/namei.c:1353:18: error: unused variable 'retval' [-Werror,-Wunused-variable]
        int i, namelen, retval;
                        ^

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>